karpenter:
  enabled: false

kuberay-operator:
  enabled: false

prometheus:
  enabled: false
  serviceMonitor:
    enabled: false

opentelemetry-collector:
  enabled: false

aws-load-balancer-controller:
  enabled: false

traefik:
  enabled: false

certManager:
  enabled: false

image:
  repository: rag8s/rag8s-onnx-embedder-reranker-cpu-amd64
  tag: gte-modernbert
  pullPolicy: IfNotPresent

frontend:
  servicePort: 80
  image:
    repository: rag8s/rag8s-frontend
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1

rayVersion: "2.48.0"
namespace: onnx-serving
headServiceName: rag8s-onnx-ray-head-svc
rayClientPort: 10001

service:
  type: ClusterIP
  httpPort: 8000
  grpcPort: 9000
  metricsPort: 8080

pvc:
  create: true
  name: rag8s-models-pvc
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  size: 50Gi

serviceAccount:
  create: true
  name: rag8s-sa

head:
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  replicas: 1

worker:
  groupName: onnx-workers
  minReplicas: 1
  maxReplicas: 2
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 5
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
  startup:
    failureThreshold: 60
    periodSeconds: 10

pdb:
  headMinAvailable: 1
  workerMinAvailable: 1

network:
  prometheusNamespace: monitoring

env:
  HF_HOME: /workspace/models/hf
  MODEL_DIR: /workspace/models/onnx
  MODEL_EMBEDDER_NAME: RAG8s/gte-modernbert-base-onnx-int8
  MODEL_RERANKER_NAME: RAG8s/gte-reranker-modernbert-base-onnx-int8
  EMBEDDER_ONNX_PATH: /workspace/models/onnx/gte-modernbert-base-onnx-int8/onnx/model_int8.onnx
  EMBEDDER_CONFIG_PATH: /workspace/models/onnx/gte-modernbert-base-onnx-int8/config.json
  EMBEDDER_TOKENIZER_PATH: /workspace/models/onnx/gte-modernbert-base-onnx-int8/tokenizer.json
  EMBEDDER_TOKENIZER_CONFIG_PATH: /workspace/models/onnx/gte-modernbert-base-onnx-int8/tokenizer_config.json
  EMBEDDER_SPECIAL_TOKENS_MAP_PATH: /workspace/models/onnx/gte-modernbert-base-onnx-int8/special_tokens_map.json
  RERANKER_ONNX_PATH: /workspace/models/onnx/gte-reranker-modernbert-base-onnx-int8/onnx/model_int8.onnx
  RERANKER_CONFIG_PATH: /workspace/models/onnx/gte-reranker-modernbert-base-onnx-int8/config.json
  RERANKER_TOKENIZER_PATH: /workspace/models/onnx/gte-reranker-modernbert-base-onnx-int8/tokenizer.json
  RERANKER_TOKENIZER_CONFIG_PATH: /workspace/models/onnx/gte-reranker-modernbert-base-onnx-int8/tokenizer_config.json
  RERANKER_SPECIAL_TOKENS_MAP_PATH: /workspace/models/onnx/gte-reranker-modernbert-base-onnx-int8/special_tokens_map.json
  EMBEDDER_OMP_NUM_THREADS: "1"
  RERANKER_OMP_NUM_THREADS: "1"
  EMBEDDER_BATCH_MAX_SIZE: "8"
  RERANKER_BATCH_MAX_SIZE: "4"
  EMBEDDER_BATCH_WAIT_TIMEOUT_S: "0.05"
  RERANKER_BATCH_WAIT_TIMEOUT_S: "0.1"
  EMBEDDER_NUM_CPUS: "1"
  RERANKER_NUM_CPUS: "1"
  PROMETHEUS_DISABLED: "1"
  PROMETHEUS_MULTIPROC_DIR: "/tmp/prometheus_multiproc"
  LOG_LEVEL: "INFO"
  OMP_NUM_THREADS: "1"
  MKL_NUM_THREADS: "1"

labels:
  app: rag8s
  component: rag8s-onnx

rbac:
  create: false

imagePullSecrets: []
tolerations: []
nodeSelector: {}
affinity: {}
createNamespace: true
podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

ingress:
  enabled: false
  controller: "traefik"
  className: ""
  annotations: {}
  hosts: []
  tls: []
  alb:
    scheme: "internet-facing"
    targetType: "ip"
    ipAddressType: "ipv4"
    certificateARN: ""
    annotations: {}
  traefik:
    createService: false
    serviceAnnotations: {}
    selector: {}
    entryPoints:
      - "web"
      - "websecure"
