{{- if .Values.reranker.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fastembed.roleName" (dict "service" "reranker") }}
  namespace: {{ .Values.reranker.namespace }}
  labels:
    {{- include "fastembed.labels" (dict "Chart" .Chart "Release" .Release "name" "reranker" "component" "reranker" "instance" "reranker") | nindent 4 }}
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  - endpoints
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
{{- end }}