replicaCount: 1
image:
  repository: docker.io/qdrant/qdrant
  tag: v1.17.1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
persistence:
  enabled: true
  size: 20Gi
  accessModes:
  - ReadWriteOnce
podAnnotations:
  app.kubernetes.io/managed-by: qdrant_service.py
  qdrant/config-checksum: 79095c918a3a96dfa9c0c40b7d8b8e919aa016fe11390918107265ee24771655
podLabels:
  app.kubernetes.io/managed-by: qdrant_service.py
resources:
  requests:
    cpu: '1'
    memory: 2Gi
  limits:
    cpu: '1'
    memory: 2Gi
config:
  cluster:
    enabled: true
    p2p:
      port: 6335
      enable_tls: false
    consensus:
      tick_period_ms: 100
  service:
    enable_tls: false
  log_level: INFO
  on_disk_payload: false
updateVolumeFsOwnership: true
podManagementPolicy: Parallel
lifecycle:
  preStop:
    exec:
      command:
      - sleep
      - '3'
