{{- if .Values.reranker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastembed.serviceName" (dict "service" "reranker") }}
  namespace: {{ .Values.reranker.namespace }}
  labels:
    {{- include "fastembed.labels" (dict "Chart" .Chart "Release" .Release "name" "reranker" "component" "reranker" "instance" "reranker") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8202
    targetPort: 8202
    protocol: TCP
    name: http
  selector:
    {{- include "fastembed.selectorLabels" (dict "name" "reranker" "component" "reranker" "instance" "reranker") | nindent 4 }}
{{- end }}