apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nginx
  namespace: inference
  labels:
    app.kubernetes.io/name: frontend-nginx
    app.kubernetes.io/component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-nginx
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend-nginx
        app.kubernetes.io/component: frontend
      annotations:
        nginx/config-checksum: 6df84896895468afbce16c6ed09d94f88e9c9fe323065efde1e55fa5e1fd38e3
    spec:
      serviceAccountName: frontend-nginx
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 101
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: tmp
        emptyDir: {}
      containers:
      - name: nginx
        image: ghcr.io/athithya-sakthivel/frontend:2026-05-02-07-05--02a4032@sha256:bec20a1a54e6ea49738dcac641a2c757d7f7af489f1f5ad7e00cb20133ac7185
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: tmp
          mountPath: /tmp
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 1
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 5
          failureThreshold: 36
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101
          capabilities:
            drop:
            - ALL
