apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-routes-reference
  namespace: inference
  labels:
    app.kubernetes.io/name: frontend-nginx
    app.kubernetes.io/component: frontend
data:
  routes.yaml: |
    tunnel: default-tunnel-1
    ingress:
      - hostname: auth.athithya.site
        service: http://zitadel.zitadel.svc.cluster.local:8080
      - hostname: api.athithya.site
        service: http://frontend-nginx.inference.svc.cluster.local:8080
      - hostname: athithya.site
        service: http://frontend-nginx.inference.svc.cluster.local:8080
      - service: http_status:404
