apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-routes-reference
  namespace: inference
  labels:
    app.kubernetes.io/name: frontend-nginx
    app.kubernetes.io/component: frontend
data:
  routes.txt: |
    frontend host: https://athithya.site
    api host: https://api.athithya.site
    auth host: https://auth.athithya.site
    public: /healthz
    public: /readyz
    public: /auth/login
    public: /auth/logout
    public: /outpost.goauthentik.io/*
    protected: /
    protected: /api/*
    protected: /generate
    protected: /generate/stream
    protected: /stream
    protected: /retrieve
