repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd6
    hooks:
      - id: gitleaks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: aca6d4c
    hooks:
      - id: ruff-check
