---
# Source: rag8s/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    name: infra
---
# Source: rag8s/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
# Source: rag8s/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: indexing
  labels:
    name: indexing
---
# Source: rag8s/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: inference
  labels:
    name: inference
---
# Source: rag8s/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    name: frontend
---
# Source: rag8s/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    name: db
---
# Source: rag8s/templates/namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
# Source: rag8s/templates/embedder-reranker-rayservice.yaml
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rag8s-rag8s-serve
  namespace: inference
  labels:
    app.kubernetes.io/name: rag8s
    app.kubernetes.io/instance: rag8s
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: rag8s-0.0.1
spec:
  rayClusterConfig:
    rayVersion: 2.48.0
    headGroupSpec:
      template:
        spec:

          volumes:
            - name: model-volume
              emptyDir: {}

          containers:
            - name: ray-head
              image: "registry.example.com/rag8s-onnx:latest"
              ports:
                - containerPort: 8000
                - containerPort: 9000
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  cpu: 1
                  memory: 2Gi
              volumeMounts:
                - name: model-volume
                  mountPath: /opt/models

    workerGroupSpecs:
      - groupName: worker
        minReplicas: 1
        maxReplicas: 4
        template:
          spec:

            volumes:
              - name: model-volume
                emptyDir: {}

            containers:
              - name: ray-worker
                image: "registry.example.com/rag8s-onnx:latest"
                ports:
                  - containerPort: 8000
                  - containerPort: 9000
                resources:
                  requests:
                    cpu: 500m
                    memory: 1Gi
                  limits:
                    cpu: 1
                    memory: 2Gi
                volumeMounts:
                  - name: model-volume
                    mountPath: /opt/models

  serveConfigV2: |
    applications:
      - name: embedder-reranker-app
        import_path: rayserve-embedder-reranker:RayService
        runtime_env:
          working_dir: /app
        deployments:
          - name: EmbedderServicer
            route_prefix: "/embed"
            ray_actor_options:
              num_cpus: 1
            autoscaling_config:
              min_replicas: 1
              max_replicas: 4
              target_num_ongoing_requests_per_replica: 10
          - name: RerankerServicer
            route_prefix: "/rerank"
            ray_actor_options:
              num_cpus: 1
            autoscaling_config:
              min_replicas: 1
              max_replicas: 2
              target_num_ongoing_requests_per_replica: 5
