apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rag8s-embedder-reranker-serve
  namespace: inference
spec:
  rayClusterConfig:
    rayVersion: "{{ .Values.EmbedderReranker.rayVersion }}"
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        spec:
          containers:
            - name: ray-head
              image: "{{ .Values.EmbedderReranker.image.repository }}:{{ .Values.EmbedderReranker.image.tag }}"
              imagePullPolicy: {{ .Values.EmbedderReranker.image.pullPolicy }}
              resources:
                requests:
                  cpu: "1"
                  memory: "2Gi"
                limits:
                  cpu: "1"
                  memory: "2Gi"
              volumeMounts:
                - name: model-volume
                  mountPath: /opt/models
          volumes:
            - name: model-volume
              emptyDir: {}
    workerGroupSpecs:
      - groupName: worker
        minReplicas: 1
        maxReplicas: 2
        template:
          spec:
            containers:
              - name: ray-worker
                image: "{{ .Values.EmbedderReranker.image.repository }}:{{ .Values.EmbedderReranker.image.tag }}"
                imagePullPolicy: {{ .Values.EmbedderReranker.image.pullPolicy }}
                resources:
                  requests:
                    cpu: "500m"
                    memory: "1Gi"
                  limits:
                    cpu: "1"
                    memory: "1Gi"
                volumeMounts:
                  - name: model-volume
                    mountPath: /opt/models
            volumes:
              - name: model-volume
                emptyDir: {}

  serveConfigV2: |
    applications:
      - name: embedder-reranker-app
        import_path: rayserve-embedder-reranker:RayService
        runtime_env:
          working_dir: /app
        deployments:
          - name: EmbedderServicer
            ray_actor_options:
              num_cpus: {{ .Values.EmbedderReranker.embedder.numCPUs }}
            autoscaling_config:
              min_replicas: {{ .Values.EmbedderReranker.embedder.minReplicas }}
              max_replicas: {{ .Values.EmbedderReranker.embedder.maxReplicas }}
              target_num_ongoing_requests_per_replica: {{ .Values.EmbedderReranker.embedder.targetOngoingRequestsPerReplica }}
          - name: RerankerServicer
            ray_actor_options:
              num_cpus: {{ .Values.EmbedderReranker.reranker.numCPUs }}
            autoscaling_config:
              min_replicas: {{ .Values.EmbedderReranker.reranker.minReplicas }}
              max_replicas: {{ .Values.EmbedderReranker.reranker.maxReplicas }}
              target_num_ongoing_requests_per_replica: {{ .Values.EmbedderReranker.reranker.targetOngoingRequestsPerReplica }}
