---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    name: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: indexing
  labels:
    name: indexing
---
apiVersion: v1
kind: Namespace
metadata:
  name: inference
  labels:
    name: inference
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    name: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    name: db
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
