{{- $relname := .Release.Name -}}
{{- $relns := .Release.Namespace -}}

apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    name: infra
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ $relname }}
    meta.helm.sh/release-namespace: {{ $relns }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ $relname }}
    meta.helm.sh/release-namespace: {{ $relns }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: indexing
  labels:
    name: indexing
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ $relname }}
    meta.helm.sh/release-namespace: {{ $relns }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: inference
  labels:
    name: inference
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ $relname }}
    meta.helm.sh/release-namespace: {{ $relns }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    name: frontend
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ $relname }}
    meta.helm.sh/release-namespace: {{ $relns }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    name: db
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ $relname }}
    meta.helm.sh/release-namespace: {{ $relns }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ $relname }}
    meta.helm.sh/release-namespace: {{ $relns }}
