apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: e2e-rag-system
  namespace: argocd
spec:
  description: "Controlled project for E2E RAG system services"
  sourceRepos:
    - https://github.com/Athithya-Sakthivel/E2E-RAG-System.git
    - https://qdrant.github.io/qdrant-helm
    - https://charts.signoz.io
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
