apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    # ── Grafana Helm chart ─────────────────────────────
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 12.3.0
      helm:
        values: |
          admin:
            existingSecret: grafana-admin
          service:
            type: ClusterIP
            port: 80
          persistence:
            enabled: false
          sidecar:
            dashboards:
              enabled: true
              searchNamespace: grafana
              label: grafana_dashboard
            datasources:
              enabled: true
              searchNamespace: grafana
              label: grafana_datasource
          env:
            GF_METRICS_ENABLED: "true"
            GF_SERVER_PROTOCOL: http
    # ── ConfigMaps from your Git repo ───────────────────
    - repoURL: https://github.com/Athithya-Sakthivel/E2E-RAG-System.git
      targetRevision: main
      path: src/manifests/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/versions
    - group: ""
      kind: ConfigMap
      jsonPointers:
        - /data