apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
  labels:
    app.kubernetes.io/name: signoz
    app.kubernetes.io/managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://charts.signoz.io
    chart: signoz
    targetRevision: "0.120.0"
    helm:
      values: |
        clickhouse:
          enabled: true
        signoz:
          env:
            SIGNOZ_TOKENIZER_JWT_SECRET:
              valueFrom:
                secretKeyRef:
                  name: "signoz-jwt-secret"
                  key: SIGNOZ_TOKENIZER_JWT_SECRET
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
