version: '3.8'

services:
  qdrant:
    image: "${QDRANT_IMAGE:-qdrant/qdrant:latest}"
    container_name: qdrant
    ports:
      - "6334:6334"
      - "6333:6333"  
    volumes:
      - ./backups/dbs/qdrant:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: "6334"
    networks:
      rag-net:
        aliases:
          - qdrant.local
    restart: unless-stopped

  valkey:
    image: "${VALKEY_IMAGE:-valkey/valkey:latest}"
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - ./backups/dbs/valkey:/data
    command: ["valkey-server", "--appendonly", "yes"]
    networks:
      rag-net:
        aliases:
          - valkey.local
    restart: unless-stopped

  arangodb:
    image: "${ARANGO_IMAGE:-arangodb/arangodb:latest}"
    container_name: arangodb
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: "${ARANGO_PASSWORD:-myarrango414}"
    volumes:
      - ./backups/dbs/arangodb:/var/lib/arangodb3
      - ./backups/dbs/arangodb-apps:/var/lib/arangodb3-apps
    networks:
      rag-net:
        aliases:
          - arangodb.local
    restart: unless-stopped

networks:
  rag-net:
    name: rag-net
    driver: bridge
