{{- /*
RayJob for indexing pipeline (values-driven).
Guarded with defaults to avoid nil-pointer/template errors.
Expected values at: .Values.rayjobs.indexing
*/ -}}
{{- $root := . -}}
{{- $rj := $root.Values.rayjobs.indexing | default dict -}}

# Namespace resolution: explicit rayjobs.namespace -> values.namespaces.indexing -> release/global namespace
{{- $ns := default (default $root.Values.namespaces.indexing $rj.namespace) (include "rag8s.namespace" $root) -}}

# Safe locals for common nested maps (use default dict to avoid nil pointer)
{{- $defaultProvisioner := "cpu-provisioner" -}}
{{- $head := $rj.head | default dict -}}
{{- $worker := $rj.worker | default dict -}}
{{- $res := $rj.resources | default dict -}}
{{- $headRes := $res.head | default dict -}}
{{- $workerRes := $res.worker | default dict -}}
{{- $headNodeSelector := default (dict "karpenter.sh/provisioner-name" $defaultProvisioner) (or $head.nodeSelector $rj.nodeSelector $rj.headNodeSelector) -}}
{{- $workerNodeSelector := default (dict "karpenter.sh/provisioner-name" $defaultProvisioner) (or $worker.nodeSelector $rj.nodeSelector $rj.workerNodeSelector) -}}
{{- $headTolerations := default list $head.tolerations -}}
{{- $workerTolerations := default list $worker.tolerations -}}
{{- $headAffinity := default dict $head.affinity -}}
{{- $workerAffinity := default dict $worker.affinity -}}
{{- $imagePullPolicy := default "IfNotPresent" $rj.imagePullPolicy -}}
{{- $imagePullSecretsHead := default list $head.imagePullSecrets -}}
{{- $imagePullSecretsWorker := default list $worker.imagePullSecrets -}}

apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: {{ default "rag8s-indexing" $rj.name | quote }}
  namespace: {{ $ns | quote }}
  labels:
{{ include "rag8s.labels" $root | indent 4 }}
spec:
  entrypoint: {{ default "python scripts/index_documents.py --source s3://my-bucket" $rj.entrypoint | quote }}
  runtimeEnvYAML: |
    working_dir: {{ default (default "/work" $rj.workingDir) $rj.workingDir | quote }}
    {{- if $rj.pip }}
    pip:
{{ toYaml $rj.pip | indent 6 }}
    {{- end }}
  ttlSecondsAfterFinished: {{ default 3600 $rj.ttlSecondsAfterFinished }}
  shutdownAfterJobFinishes: {{ default true $rj.shutdownAfterJobFinishes }}
  submissionMode: {{ default "KubernetesJob" $rj.submissionMode | quote }}
  rayClusterSpec:
    rayVersion: {{ default "2.10.0" $rj.rayVersion | quote }}
    headGroupSpec:
      serviceType: {{ default "ClusterIP" (default $rj.headServiceType (index $rj "headServiceType")) | quote }}
      template:
        metadata:
          annotations:
            {{- if $head.annotations }}
{{ toYaml $head.annotations | nindent 12 }}
            {{- end }}
        spec:
          nodeSelector:
{{ toYaml $headNodeSelector | indent 12 }}
          {{- if $headTolerations }}
          tolerations:
{{ toYaml $headTolerations | indent 12 }}
          {{- end }}
          {{- if $headAffinity }}
          affinity:
{{ toYaml $headAffinity | indent 12 }}
          {{- end }}
          {{- if $imagePullSecretsHead }}
          imagePullSecrets:
{{ toYaml $imagePullSecretsHead | indent 12 }}
          {{- end }}
          containers:
            - name: ray-head
              image: {{ default "myrepo/rag8s-indexer:latest" $rj.image | quote }}
              imagePullPolicy: {{ $imagePullPolicy | quote }}
              resources:
                requests:
                  cpu: {{ default "250m" $headRes.cpu | quote }}
                  memory: {{ default "512Mi" $headRes.memory | quote }}
                limits:
                  cpu: {{ default (or $headRes.cpu "250m") (or $headRes.cpu "250m") | quote }}
                  memory: {{ default (or $headRes.memory "512Mi") (or $headRes.memory "512Mi") | quote }}

    workerGroupSpecs:
      - groupName: workers
        replicas: {{ default 1 $rj.workerReplicas }}
        minReplicas: {{ default 1 $rj.workerMin }}
        maxReplicas: {{ default 4 $rj.workerMax }}
        template:
          metadata:
            annotations:
              {{- if $worker.annotations }}
{{ toYaml $worker.annotations | nindent 12 }}
              {{- end }}
          spec:
            nodeSelector:
{{ toYaml $workerNodeSelector | indent 12 }}
            {{- if $workerTolerations }}
            tolerations:
{{ toYaml $workerTolerations | indent 12 }}
            {{- end }}
            {{- if $workerAffinity }}
            affinity:
{{ toYaml $workerAffinity | indent 12 }}
            {{- end }}
            {{- if $imagePullSecretsWorker }}
            imagePullSecrets:
{{ toYaml $imagePullSecretsWorker | indent 12 }}
            {{- end }}
            containers:
              - name: ray-worker
                image: {{ default "myrepo/rag8s-indexer:latest" $rj.image | quote }}
                imagePullPolicy: {{ $imagePullPolicy | quote }}
                resources:
                  requests:
                    cpu: {{ default "250m" $workerRes.cpu | quote }}
                    memory: {{ default "512Mi" $workerRes.memory | quote }}
                  limits:
                    cpu: {{ default (or $workerRes.cpu "250m") (or $workerRes.cpu "250m") | quote }}
                    memory: {{ default (or $workerRes.memory "512Mi") (or $workerRes.memory "512Mi") | quote }}
