{{- $root := . -}}
{{- $rj := $root.Values.rayjobs.indexing | default dict -}}
{{- $ns := default $root.Values.namespaces.indexing $root.Values.rayjobs.namespace | default $root.Release.Namespace -}}
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: {{ $rj.name | quote }}
  namespace: {{ $ns }}
spec:
  entrypoint: {{ $rj.entrypoint | quote }}
  runtimeEnvYAML: |
    working_dir: {{ $rj.workingDir | quote }}
    pip:
{{ toYaml $rj.pip | indent 6 }}
  ttlSecondsAfterFinished: {{ default 3600 $rj.ttlSecondsAfterFinished }}
  shutdownAfterJobFinishes: true
  submissionMode: KubernetesJob
  rayClusterSpec:
    rayVersion: {{ $rj.rayVersion | quote }}
    headGroupSpec:
      serviceType: ClusterIP
      template:
        spec:
          nodeSelector:
            karpenter.sh/provisioner-name: cpu-provisioner
          containers:
            - name: ray-head
              image: {{ $rj.image | quote }}
              resources:
                requests:
                  cpu: {{ $rj.resources.head.cpu | quote }}
                  memory: {{ $rj.resources.head.memory | quote }}
                limits:
                  cpu: {{ $rj.resources.head.cpu | quote }}
                  memory: {{ $rj.resources.head.memory | quote }}
    workerGroupSpecs:
      - replicas: {{ $rj.workerReplicas | default 1 }}
        minReplicas: {{ $rj.workerMin | default 1 }}
        maxReplicas: {{ $rj.workerMax | default 4 }}
        groupName: workers
        template:
          spec:
            nodeSelector:
              karpenter.sh/provisioner-name: cpu-provisioner
            containers:
              - name: ray-worker
                image: {{ $rj.image | quote }}
                resources:
                  requests:
                    cpu: {{ $rj.resources.worker.cpu | quote }}
                    memory: {{ $rj.resources.worker.memory | quote }}
                  limits:
                    cpu: {{ $rj.resources.worker.cpu | quote }}
                    memory: {{ $rj.resources.worker.memory | quote }}
