apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-netpol
  namespace: {{ .Values.namespace | quote }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {} # allow intra-namespace traffic
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.network.prometheusNamespace | default "monitoring" }}
  egress:
    - to:
        - podSelector: {} # allow intra-namespace egress
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
