{{- if .Values.sparse.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fastembed.serviceAccountName" (dict "service" "sparse") }}
  namespace: {{ .Values.sparse.namespace }}
  labels:
    {{- include "fastembed.labels" (dict "Chart" .Chart "Release" .Release "name" "sparse" "component" "embedder" "instance" "sparse") | nindent 4 }}
{{- end }}