{{- $root := . -}}
{{- $vals := $root.Values.rayservices.onnxEmbedderReranker | default dict -}}
{{- if not (default false $vals.enabled) -}}
{{- else -}}
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: {{ default "rag8s-embedder-reranker-serve" $vals.name | quote }}
  namespace: {{ default (include "rag8s.namespace" $root) $vals.namespace | quote }}
  labels:
    app.kubernetes.io/name: embedder-reranker
    app.kubernetes.io/instance: {{ $root.Release.Name | quote }}
    {{- include "rag8s.labels" $root | nindent 4 }}
spec:
  rayClusterConfig:
    rayVersion: {{ default "2.48.0" $vals.ray.version | quote }}
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        spec:
          serviceAccountName: {{ default "ray-inference-sa" $vals.serviceAccountName | quote }}
          containers:
            - name: ray-head
              image: "{{ default "rayproject/ray:2.48.0" (printf "%s:%s" $vals.ray.image.repository $vals.ray.image.tag) }}"
              imagePullPolicy: {{ default "IfNotPresent" $vals.ray.image.pullPolicy }}
              env:
                - name: RAY_NODE_ROLE
                  value: "head"
              ports:
                - containerPort: 8265
                - containerPort: 8000
                - containerPort: 9000
          volumes:
            - name: model-volume
              emptyDir: {}
    workerGroupSpecs:
      - groupName: worker
        minReplicas: {{ default 1 (default (index $vals "worker").minReplicas) }}
        maxReplicas: {{ default 4 (default (index $vals "worker").maxReplicas) }}
        template:
          spec:
            serviceAccountName: {{ default "ray-inference-sa" $vals.serviceAccountName | quote }}
            containers:
              - name: ray-worker
                image: "{{ default "rayproject/ray:2.48.0" (printf "%s:%s" $vals.ray.image.repository $vals.ray.image.tag) }}"
                imagePullPolicy: {{ default "IfNotPresent" $vals.ray.image.pullPolicy }}
                env:
                  - name: RAY_NODE_ROLE
                    value: "worker"
            volumes:
              - name: model-volume
                emptyDir: {}
  serveConfigV2: |
    applications:
      - name: embedder-reranker-app
        import_path: {{ $vals.importPath | default "rayserve-embedder-reranker" | quote }}
        runtime_env:
          working_dir: {{ $vals.runtimeWorkingDir | default "/app" | quote }}
        deployments:
          - name: EmbedderServicer
            route_prefix: "/embed"
            ray_actor_options:
              num_cpus: {{ default 1 (default (index $vals "embedder").numCPUs) }}
          - name: RerankerServicer
            route_prefix: "/rerank"
            ray_actor_options:
              num_cpus: {{ default 1 (default (index $vals "reranker").numCPUs) }}
{{- end }}
