{{- if .Values.rayservices.onnxEmbedderReranker.enabled }}
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: {{ default "rag8s-embedder-reranker-serve" .Values.rayservices.onnxEmbedderReranker.name | quote }}
  namespace: {{ default .Release.Namespace .Values.rayservices.onnxEmbedderReranker.namespace }}
  labels:
    app.kubernetes.io/name: embedder-reranker
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  rayClusterConfig:
    rayVersion: {{ .Values.rayservices.onnxEmbedderReranker.ray.version | quote }}

    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        metadata:
          annotations:
            {{- if .Values.rayservices.onnxEmbedderReranker.head.annotations }}
{{ toYaml .Values.rayservices.onnxEmbedderReranker.head.annotations | nindent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ .Values.rayservices.onnxEmbedderReranker.serviceAccountName }}
          {{- if .Values.rayservices.onnxEmbedderReranker.imagePullSecrets }}
          imagePullSecrets:
            {{- range .Values.rayservices.onnxEmbedderReranker.imagePullSecrets }}
            - name: {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.rayservices.onnxEmbedderReranker.head.nodeSelector }}
          nodeSelector:
{{ toYaml .Values.rayservices.onnxEmbedderReranker.head.nodeSelector | indent 12 }}
          {{- end }}
          {{- if .Values.rayservices.onnxEmbedderReranker.head.tolerations }}
          tolerations:
{{ toYaml .Values.rayservices.onnxEmbedderReranker.head.tolerations | indent 12 }}
          {{- end }}
          {{- if .Values.rayservices.onnxEmbedderReranker.head.affinity }}
          affinity:
{{ toYaml .Values.rayservices.onnxEmbedderReranker.head.affinity | indent 12 }}
          {{- end }}

          containers:
            - name: ray-head
              image: "{{ .Values.rayservices.onnxEmbedderReranker.ray.image.repository }}:{{ .Values.rayservices.onnxEmbedderReranker.ray.image.tag }}"
              imagePullPolicy: {{ .Values.rayservices.onnxEmbedderReranker.ray.image.pullPolicy | default "IfNotPresent" }}
              env:
                - name: RAY_NODE_ROLE
                  value: "head"
                - name: RAY_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                {{- if .Values.rayservices.onnxEmbedderReranker.env }}
{{ toYaml .Values.rayservices.onnxEmbedderReranker.env | indent 16 }}
                {{- end }}
              resources:
                requests:
                  cpu: {{ .Values.rayservices.onnxEmbedderReranker.ray.head.cpu.request | quote }}
                  memory: {{ .Values.rayservices.onnxEmbedderReranker.ray.head.memory.request | quote }}
                limits:
                  cpu: {{ .Values.rayservices.onnxEmbedderReranker.ray.head.cpu.limit | quote }}
                  memory: {{ .Values.rayservices.onnxEmbedderReranker.ray.head.memory.limit | quote }}
              ports:
                - containerPort: 8265
                - containerPort: 8000
                - containerPort: 9000
              volumeMounts:
                - name: model-volume
                  mountPath: {{ .Values.rayservices.onnxEmbedderReranker.modelMountPath | default "/opt/models" }}
{{- if .Values.rayservices.onnxEmbedderReranker.useHostPath }}
                  readOnly: true
{{- end }}
              readinessProbe:
                httpGet:
                  path: /
                  port: 8265
                initialDelaySeconds: 10
                periodSeconds: 10
                failureThreshold: 6
              livenessProbe:
                httpGet:
                  path: /
                  port: 8265
                initialDelaySeconds: 60
                periodSeconds: 30
                failureThreshold: 5

          volumes:
            - name: model-volume
{{- if .Values.rayservices.onnxEmbedderReranker.useHostPath }}
              hostPath:
                path: {{ .Values.rayservices.onnxEmbedderReranker.hostPath }}
                type: DirectoryOrCreate
{{- else if .Values.rayservices.onnxEmbedderReranker.usePVC }}
              persistentVolumeClaim:
                claimName: {{ .Values.rayservices.onnxEmbedderReranker.modelPVC }}
{{- else }}
              emptyDir: {}
{{- end }}

    workerGroupSpecs:
      - groupName: worker
        minReplicas: {{ .Values.rayservices.onnxEmbedderReranker.ray.workers.minReplicas }}
        maxReplicas: {{ .Values.rayservices.onnxEmbedderReranker.ray.workers.maxReplicas }}
        template:
          metadata:
            annotations:
              {{- if .Values.rayservices.onnxEmbedderReranker.worker.annotations }}
{{ toYaml .Values.rayservices.onnxEmbedderReranker.worker.annotations | nindent 14 }}
              {{- end }}
          spec:
            {{- if .Values.rayservices.onnxEmbedderReranker.worker.serviceAccountName }}
            serviceAccountName: {{ .Values.rayservices.onnxEmbedderReranker.worker.serviceAccountName }}
            {{- end }}
            {{- if .Values.rayservices.onnxEmbedderReranker.imagePullSecrets }}
            imagePullSecrets:
              {{- range .Values.rayservices.onnxEmbedderReranker.imagePullSecrets }}
              - name: {{ . }}
              {{- end }}
            {{- end }}
            {{- if .Values.rayservices.onnxEmbedderReranker.worker.nodeSelector }}
            nodeSelector:
{{ toYaml .Values.rayservices.onnxEmbedderReranker.worker.nodeSelector | indent 14 }}
            {{- end }}
            {{- if .Values.rayservices.onnxEmbedderReranker.worker.tolerations }}
            tolerations:
{{ toYaml .Values.rayservices.onnxEmbedderReranker.worker.tolerations | indent 14 }}
            {{- end }}
            {{- if .Values.rayservices.onnxEmbedderReranker.worker.affinity }}
            affinity:
{{ toYaml .Values.rayservices.onnxEmbedderReranker.worker.affinity | indent 14 }}
            {{- end }}

            containers:
              - name: ray-worker
                image: "{{ .Values.rayservices.onnxEmbedderReranker.ray.image.repository }}:{{ .Values.rayservices.onnxEmbedderReranker.ray.image.tag }}"
                imagePullPolicy: {{ .Values.rayservices.onnxEmbedderReranker.ray.image.pullPolicy | default "IfNotPresent" }}
                env:
                  - name: RAY_NODE_ROLE
                    value: "worker"
                  - name: RAY_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  {{- if .Values.rayservices.onnxEmbedderReranker.env }}
{{ toYaml .Values.rayservices.onnxEmbedderReranker.env | indent 18 }}
                  {{- end }}
                resources:
                  requests:
                    cpu: {{ .Values.rayservices.onnxEmbedderReranker.ray.workers.cpu.request | quote }}
                    memory: {{ .Values.rayservices.onnxEmbedderReranker.ray.workers.memory.request | quote }}
                  limits:
                    cpu: {{ .Values.rayservices.onnxEmbedderReranker.ray.workers.cpu.limit | quote }}
                    memory: {{ .Values.rayservices.onnxEmbedderReranker.ray.workers.memory.limit | quote }}
                ports:
                  - containerPort: 8000
                  - containerPort: 9000
                volumeMounts:
                  - name: model-volume
                    mountPath: {{ .Values.rayservices.onnxEmbedderReranker.modelMountPath | default "/opt/models" }}
            readinessProbe:
              httpGet:
                path: /
                port: 8265
              initialDelaySeconds: 15
              periodSeconds: 15
              failureThreshold: 6

            volumes:
              - name: model-volume
{{- if .Values.rayservices.onnxEmbedderReranker.useHostPath }}
                hostPath:
                  path: {{ .Values.rayservices.onnxEmbedderReranker.hostPath }}
                  type: DirectoryOrCreate
{{- else if .Values.rayservices.onnxEmbedderReranker.usePVC }}
                persistentVolumeClaim:
                  claimName: {{ .Values.rayservices.onnxEmbedderReranker.modelPVC }}
{{- else }}
                emptyDir: {}
{{- end }}

  serveConfigV2: |
    applications:
      - name: embedder-reranker-app
        import_path: {{ .Values.rayservices.onnxEmbedderReranker.importPath }}
        runtime_env:
          working_dir: {{ .Values.rayservices.onnxEmbedderReranker.runtimeWorkingDir }}
        deployments:
          - name: EmbedderServicer
            route_prefix: "/embed"
            ray_actor_options:
              num_cpus: {{ .Values.rayservices.onnxEmbedderReranker.embedder.numCPUs }}
            autoscaling_config:
              min_replicas: {{ .Values.rayservices.onnxEmbedderReranker.embedder.autoscale.minReplicas }}
              max_replicas: {{ .Values.rayservices.onnxEmbedderReranker.embedder.autoscale.maxReplicas }}
              target_num_ongoing_requests_per_replica: {{ .Values.rayservices.onnxEmbedderReranker.embedder.autoscale.targetRequestsPerReplica }}
          - name: RerankerServicer
            route_prefix: "/rerank"
            ray_actor_options:
              num_cpus: {{ .Values.rayservices.onnxEmbedderReranker.reranker.numCPUs }}
            autoscaling_config:
              min_replicas: {{ .Values.rayservices.onnxEmbedderReranker.reranker.autoscale.minReplicas }}
              max_replicas: {{ .Values.rayservices.onnxEmbedderReranker.reranker.autoscale.maxReplicas }}
              target_num_ongoing_requests_per_replica: {{ .Values.rayservices.onnxEmbedderReranker.reranker.autoscale.targetRequestsPerReplica }}
{{- end }}
