{{- $root := . -}}
{{- $vals := $root.Values.rayservices.sglang | default dict -}}
{{- if not (default false $vals.enabled) -}}
{{- else -}}
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: {{ default "rag8s-sglang-serve" $vals.name | quote }}
  namespace: {{ default $root.Release.Namespace $vals.namespace }}
  labels:
    app.kubernetes.io/name: sglang
    app.kubernetes.io/instance: {{ $root.Release.Name }}
spec:
  rayClusterConfig:
    rayVersion: {{ $vals.ray.version | quote }}

    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        metadata:
          annotations:
            {{- if $vals.head.annotations }}
{{ toYaml $vals.head.annotations | nindent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ default $vals.serviceAccountName "ray-inference-sa" }}
          {{- if $vals.imagePullSecrets }}
          imagePullSecrets:
            {{- range $vals.imagePullSecrets }}
            - name: {{ . }}
            {{- end }}
          {{- end }}
          {{- $headNS := default (dict "karpenter.sh/provisioner-name" "cpu-provisioner" "kubernetes.io/arch" "amd64") $vals.head.nodeSelector }}
          nodeSelector:
{{ toYaml $headNS | indent 12 }}
          {{- $headTol := default list $vals.head.tolerations }}
          {{- if $headTol }}
          tolerations:
{{ toYaml $headTol | indent 12 }}
          {{- end }}
          {{- if $vals.head.affinity }}
          affinity:
{{ toYaml $vals.head.affinity | indent 12 }}
          {{- end }}

          containers:
            - name: ray-head
              image: "{{ $vals.ray.image.repository }}:{{ $vals.ray.image.tag }}"
              imagePullPolicy: {{ $vals.ray.image.pullPolicy | default "IfNotPresent" }}
              env:
                - name: RAY_NODE_ROLE
                  value: "head"
                - name: RAY_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                {{- if $vals.env }}
{{ toYaml $vals.env | indent 16 }}
                {{- end }}
              resources:
                requests:
                  cpu: {{ default "1000m" $vals.ray.head.cpu.request | quote }}
                  memory: {{ default "4Gi" $vals.ray.head.memory.request | quote }}
                limits:
                  cpu: {{ default "2000m" $vals.ray.head.cpu.limit | quote }}
                  memory: {{ default "8Gi" $vals.ray.head.memory.limit | quote }}
              ports:
                - containerPort: 8265
                - containerPort: 8000
                - containerPort: 9000
              volumeMounts:
                - name: model-volume
                  mountPath: {{ $vals.modelMountPath | default "/opt/models" }}
              readinessProbe:
                httpGet:
                  path: /
                  port: 8265
                initialDelaySeconds: 15
                periodSeconds: 10
                failureThreshold: 6
              livenessProbe:
                httpGet:
                  path: /
                  port: 8265
                initialDelaySeconds: 60
                periodSeconds: 30
                failureThreshold: 5
          volumes:
            - name: model-volume
              emptyDir: {}

    workerGroupSpecs:
      - groupName: gpu-workers
        minReplicas: {{ default 1 $vals.ray.workers.minReplicas }}
        maxReplicas: {{ default 4 $vals.ray.workers.maxReplicas }}
        template:
          metadata:
            annotations:
              {{- if $vals.worker.annotations }}
{{ toYaml $vals.worker.annotations | nindent 12 }}
              {{- end }}
          spec:
            {{- $workerSA := default $vals.worker.serviceAccountName $vals.serviceAccountName }}
            {{- if $workerSA }}
            serviceAccountName: {{ $workerSA }}
            {{- end }}
            {{- if $vals.imagePullSecrets }}
            imagePullSecrets:
              {{- range $vals.imagePullSecrets }}
              - name: {{ . }}
              {{- end }}
            {{- end }}

            {{- $workerNodeSel := default (dict "karpenter.sh/provisioner-name" "gpu-provisioner" "kubernetes.io/arch" "amd64") $vals.worker.nodeSelector }}
            nodeSelector:
{{ toYaml $workerNodeSel | indent 12 }}

            {{- $workerTols := default (list (dict "key" "nvidia.com/gpu" "operator" "Exists" "effect" "NoSchedule")) $vals.worker.tolerations }}
            tolerations:
{{ toYaml $workerTols | indent 12 }}

            {{- if $vals.worker.affinity }}
            affinity:
{{ toYaml $vals.worker.affinity | indent 12 }}
            {{- end }}

            containers:
              - name: ray-gpu-worker
                image: "{{ $vals.ray.image.repository }}:{{ $vals.ray.image.tag }}"
                imagePullPolicy: {{ $vals.ray.image.pullPolicy | default "IfNotPresent" }}
                env:
                  - name: RAY_NODE_ROLE
                    value: "worker"
                  - name: RAY_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  {{- if $vals.env }}
{{ toYaml $vals.env | indent 18 }}
                  {{- end }}
                resources:
                  requests:
                    cpu: {{ default "1000m" $vals.ray.workers.cpu.request | quote }}
                    memory: {{ default "8Gi" $vals.ray.workers.memory.request | quote }}
                    nvidia.com/gpu: {{ default 1 $vals.ray.workers.gpu.request }}
                  limits:
                    cpu: {{ default "2000m" $vals.ray.workers.cpu.limit | quote }}
                    memory: {{ default "16Gi" $vals.ray.workers.memory.limit | quote }}
                    nvidia.com/gpu: {{ default 1 $vals.ray.workers.gpu.limit }}
                ports:
                  - containerPort: 8000
                  - containerPort: 9000
                volumeMounts:
                  - name: model-volume
                    mountPath: {{ $vals.modelMountPath | default "/opt/models" }}
            readinessProbe:
              httpGet:
                path: /
                port: 8265
              initialDelaySeconds: 15
              periodSeconds: 15
              failureThreshold: 6
            volumes:
              - name: model-volume
                emptyDir: {}
  serveConfigV2: |
    applications:
      - name: sglang-app
        import_path: {{ $vals.importPath | default "rayserve-sglang" }}
        runtime_env:
          working_dir: {{ $vals.runtimeWorkingDir | default "/app" }}
        deployments:
          - name: SGLangService
            route_prefix: "/sglang"
            ray_actor_options:
              num_gpus: {{ default 1 $vals.service.numGPUs }}
            autoscaling_config:
              min_replicas: {{ default 1 $vals.service.autoscale.minReplicas }}
              max_replicas: {{ default 4 $vals.service.autoscale.maxReplicas }}
              target_num_ongoing_requests_per_replica: {{ default 5 $vals.service.autoscale.targetRequestsPerReplica }}
{{- end }}
