{{- /*
RayService for SGLang (GPU LLM) — values-driven and defensive.
Renders only when .Values.rayservices.sglang.enabled is true.

Value path: .Values.rayservices.sglang
Key expectations (all optional; defaults provided):
  name, namespace
  ray:
    version
    image: { repository, tag, pullPolicy }
    head: { cpu: {request,limit}, memory: {request,limit} }
    workers: { minReplicas, maxReplicas, cpu: {request,limit}, memory: {request,limit}, gpu: {request,limit} }
  serviceAccountName
  imagePullSecrets
  modelMountPath, useHostPath, hostPath, usePVC, modelPVC
  env (map)
  head / worker: nodeSelector, tolerations, affinity, annotations
  worker.service.numGPUs or workers.gpu.*
*/ -}}
{{- $root := . -}}
{{- $vals := $root.Values.rayservices.sglang | default dict -}}
{{- if not (default false $vals.enabled) -}}
{{- else -}}

apiVersion: ray.io/v1
kind: RayService
metadata:
  name: {{ default "rag8s-sglang-serve" $vals.name | quote }}
  namespace: {{ default (include "rag8s.namespace" $root) $vals.namespace | quote }}
  labels:
    app.kubernetes.io/name: sglang
    app.kubernetes.io/instance: {{ $root.Release.Name | quote }}
    {{- include "rag8s.labels" $root | nindent 4 }}
spec:
  rayClusterConfig:
    rayVersion: {{ default "2.10.0" $vals.ray.version | quote }}

    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        metadata:
          annotations:
            {{- if $vals.head.annotations }}
{{ toYaml $vals.head.annotations | nindent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ default "ray-inference-sa" $vals.serviceAccountName | quote }}
          {{- if $vals.imagePullSecrets }}
          imagePullSecrets:
{{ toYaml $vals.imagePullSecrets | nindent 12 }}
          {{- end }}
          {{- $headNodeSel := default (dict "karpenter.sh/provisioner-name" "cpu-provisioner" "kubernetes.io/arch" "amd64") $vals.head.nodeSelector }}
          nodeSelector:
{{ toYaml $headNodeSel | indent 12 }}
          {{- $headTol := default list $vals.head.tolerations }}
          {{- if $headTol }}
          tolerations:
{{ toYaml $headTol | indent 12 }}
          {{- end }}
          {{- if $vals.head.affinity }}
          affinity:
{{ toYaml $vals.head.affinity | indent 12 }}
          {{- end }}

          containers:
            - name: ray-head
              image: "{{ default (printf "%s:%s" $vals.ray.image.repository $vals.ray.image.tag) (printf "rayproject/ray:%s" (default "2.10.0" $vals.ray.version)) }}"
              imagePullPolicy: {{ default "IfNotPresent" $vals.ray.image.pullPolicy }}
              env:
                - name: RAY_NODE_ROLE
                  value: "head"
                - name: RAY_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                {{- if $vals.env }}
{{ toYaml $vals.env | indent 16 }}
                {{- end }}
              resources:
                requests:
                  cpu: {{ default "1000m" (default (dict $vals.ray.head.cpu) (dict)).request | quote }}
                  memory: {{ default "4Gi" (default (dict $vals.ray.head.memory) (dict)).request | quote }}
                limits:
                  cpu: {{ default "2000m" (default (dict $vals.ray.head.cpu) (dict)).limit | quote }}
                  memory: {{ default "8Gi" (default (dict $vals.ray.head.memory) (dict)).limit | quote }}
              ports:
                - containerPort: 8265
                - containerPort: 8000
                - containerPort: 9000
              volumeMounts:
                - name: model-volume
                  mountPath: {{ default "/opt/models" $vals.modelMountPath | quote }}
              readinessProbe:
                httpGet:
                  path: /
                  port: 8265
                initialDelaySeconds: 15
                periodSeconds: 10
              livenessProbe:
                httpGet:
                  path: /
                  port: 8265
                initialDelaySeconds: 60
                periodSeconds: 30

          volumes:
            - name: model-volume
              emptyDir: {}

    workerGroupSpecs:
      - groupName: gpu-workers
        minReplicas: {{ default 1 (default (index $vals "ray").workers.minReplicas (default 1 (index $vals "worker").minReplicas))) }}
        maxReplicas: {{ default 4 (default (index $vals "ray").workers.maxReplicas (default 4 (index $vals "worker").maxReplicas))) }}
        template:
          metadata:
            annotations:
              {{- if $vals.worker.annotations }}
{{ toYaml $vals.worker.annotations | nindent 14 }}
              {{- end }}
          spec:
            {{- $workerSA := default $vals.serviceAccountName "ray-inference-sa" }}
            {{- if $workerSA }}
            serviceAccountName: {{ $workerSA | quote }}
            {{- end }}
            {{- if $vals.imagePullSecrets }}
            imagePullSecrets:
{{ toYaml $vals.imagePullSecrets | nindent 14 }}
            {{- end }}

            {{- $workerNodeSel := default (dict "karpenter.sh/provisioner-name" "gpu-provisioner" "kubernetes.io/arch" "amd64") $vals.worker.nodeSelector }}
            nodeSelector:
{{ toYaml $workerNodeSel | indent 14 }}

            {{- $defaultWorkerTols := list (dict "key" "nvidia.com/gpu" "operator" "Exists" "effect" "NoSchedule") }}
            {{- $workerTols := default $defaultWorkerTols $vals.worker.tolerations }}
            tolerations:
{{ toYaml $workerTols | indent 14 }}

            {{- if $vals.worker.affinity }}
            affinity:
{{ toYaml $vals.worker.affinity | indent 14 }}
            {{- end }}

            containers:
              - name: ray-gpu-worker
                image: "{{ default (printf "%s:%s" $vals.ray.image.repository $vals.ray.image.tag) (printf "rayproject/ray:%s" (default "2.10.0" $vals.ray.version)) }}"
                imagePullPolicy: {{ default "IfNotPresent" $vals.ray.image.pullPolicy }}
                env:
                  - name: RAY_NODE_ROLE
                    value: "worker"
                  - name: RAY_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                  {{- if $vals.env }}
{{ toYaml $vals.env | indent 18 }}
                  {{- end }}
                resources:
                  requests:
                    cpu: {{ default "1000m" (default (index $vals.ray.workers "cpu").request (default (index $vals.worker "cpu").request)) | quote }}
                    memory: {{ default "8Gi" (default (index $vals.ray.workers "memory").request (default (index $vals.worker "memory").request)) | quote }}
                    nvidia.com/gpu: {{ default 1 (default (index $vals.ray.workers "gpu").request (default (index $vals.worker "gpu").request))) }}
                  limits:
                    cpu: {{ default "2000m" (default (index $vals.ray.workers "cpu").limit (default (index $vals.worker "cpu").limit)) | quote }}
                    memory: {{ default "16Gi" (default (index $vals.ray.workers "memory").limit (default (index $vals.worker "memory").limit)) | quote }}
                    nvidia.com/gpu: {{ default 1 (default (index $vals.ray.workers "gpu").limit (default (index $vals.worker "gpu").limit))) }}
                ports:
                  - containerPort: 8000
                  - containerPort: 9000
                volumeMounts:
                  - name: model-volume
                    mountPath: {{ default "/opt/models" $vals.modelMountPath | quote }}
            readinessProbe:
              httpGet:
                path: /
                port: 8265
              initialDelaySeconds: 15
              periodSeconds: 15
              failureThreshold: 6
            volumes:
              - name: model-volume
                emptyDir: {}

  serveConfigV2: |
    applications:
      - name: sglang-app
        import_path: {{ $vals.importPath | default "rayserve-sglang" | quote }}
        runtime_env:
          working_dir: {{ $vals.runtimeWorkingDir | default "/app" | quote }}
        deployments:
          - name: SGLangService
            route_prefix: "/sglang"
            ray_actor_options:
              num_gpus: {{ default 1 (or (index $vals "service" "numGPUs") (default (index $vals "service").numGPUs (default (index $vals.ray.workers "gpu").request 1))) }}
            autoscaling_config:
              min_replicas: {{ default 1 (default (index $vals "service").autoscale.minReplicas (default 1 (index $vals "service").autoscale.minReplicas))) }}
              max_replicas: {{ default 4 (default (index $vals "service").autoscale.maxReplicas (default 4 (index $vals "service").autoscale.maxReplicas))) }}
              target_num_ongoing_requests_per_replica: {{ default 5 (default (index $vals "service").autoscale.targetRequestsPerReplica (default 5 (index $vals "service").autoscale.targetRequestsPerReplica))) }}
{{- end }}
