apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dense-rb
  namespace: models
subjects:
- kind: ServiceAccount
  name: dense-sa
  namespace: models
roleRef:
  kind: Role
  name: dense-role
  apiGroup: rbac.authorization.k8s.io
