rayservices:
  onnxEmbedderReranker:
    enabled: true
    name: rag8s-embedder-reranker-rayserve-cpu
    namespace: inference
    serviceAccountName: ray-inference-sa
    ray:
      version: "2.48.0"
      image:
        repository: "rag8s/rag8s-onnx-embedder-reranker-cpu"
        tag: "latest"
        pullPolicy: IfNotPresent
      head:
        cpu:
          request: "500m"
          limit: "1"
        memory:
          request: "1Gi"
          limit: "2Gi"
        nodeSelector:
          karpenter.sh/provisioner-name: cpu-provisioner
          kubernetes.io/arch: amd64
        tolerations: []
      workers:
        cpu:
          request: "500m"
          limit: "1"
        memory:
          request: "1Gi"
          limit: "1Gi"
        minReplicas: 1
        maxReplicas: 4
        nodeSelector:
          karpenter.sh/provisioner-name: cpu-provisioner
          kubernetes.io/arch: amd64
        tolerations: []
    imagePullSecrets: []
    modelMountPath: "/opt/models"
    useHostPath: false
    usePVC: false
    head:
      annotations: {}
      nodeSelector:
        karpenter.sh/provisioner-name: cpu-provisioner
        kubernetes.io/arch: amd64
      tolerations: []
      affinity: {}
    worker:
      minReplicas: 1
      maxReplicas: 4
      annotations: {}
      nodeSelector:
        karpenter.sh/provisioner-name: cpu-provisioner
        kubernetes.io/arch: amd64
      tolerations: []
      affinity: {}
    embedder:
      numCPUs: 1
      autoscale:
        minReplicas: 1
        maxReplicas: 4
        targetRequestsPerReplica: 10
    reranker:
      numCPUs: 1
      autoscale:
        minReplicas: 1
        maxReplicas: 2
        targetRequestsPerReplica: 5
    importPath: "rayserve-embedder-reranker"
    runtimeWorkingDir: "/app"
