{{- $vals := .Values }}
{{- $ns := (default "inference" $vals.namespaces.inference) }}
{{- $frontend := $vals.core.frontend | default dict }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rag8s.fullname" . }}
  namespace: {{ $ns }}
  labels:
    {{- include "rag8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ default 2 $frontend.replicas }}
  selector:
    matchLabels:
      {{- include "rag8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rag8s.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: {{ default "frontend-sa" $frontend.serviceAccount }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values: ["{{ include "rag8s.name" . }}"]
              topologyKey: kubernetes.io/hostname
      containers:
        - name: frontend
          image: "{{ default "rag8s/frontend" $frontend.image.repository }}:{{ default "latest" $frontend.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" $frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ default 8080 $frontend.port }}
          envFrom:
            - configMapRef:
                name: {{ default "rag8s-config" $frontend.configMap }}
            - secretRef:
                name: {{ default "rag8s-secrets" $frontend.secret }}
          resources:
            requests:
              cpu: {{ default "500m" (default dict $frontend.resources.requests).cpu }}
              memory: {{ default "1Gi" (default dict $frontend.resources.requests).memory }}
            limits:
              cpu: {{ default "1" (default dict $frontend.resources.limits).cpu }}
              memory: {{ default "2Gi" (default dict $frontend.resources.limits).memory }}
          readinessProbe:
            httpGet:
              path: {{ default "/health" $frontend.readiness.path }}
              port: {{ default 8080 $frontend.readiness.port }}
            initialDelaySeconds: {{ default 5 $frontend.readiness.initialDelaySeconds }}
            periodSeconds: {{ default 10 $frontend.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ default "/health" $frontend.liveness.path }}
              port: {{ default 8080 $frontend.liveness.port }}
            initialDelaySeconds: {{ default 15 $frontend.liveness.initialDelaySeconds }}
            periodSeconds: {{ default 20 $frontend.liveness.periodSeconds }}
      terminationGracePeriodSeconds: {{ default 30 $frontend.terminationGracePeriodSeconds }}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rag8s.fullname" . }}-hpa
  namespace: {{ $ns }}
  labels:
    {{- include "rag8s.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rag8s.fullname" . }}
  minReplicas: {{ default 2 (default dict $frontend.hpa).minReplicas }}
  maxReplicas: {{ default 10 (default dict $frontend.hpa).maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ default 60 (default dict $frontend.hpa).cpuTargetPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ default 70 (default dict $frontend.hpa).memoryTargetPercentage }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rag8s.fullname" . }}
  namespace: {{ $ns }}
  labels:
    {{- include "rag8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ default "ClusterIP" (default dict $frontend.service).type }}
  ports:
    - port: {{ default 80 (default dict $frontend.service).port }}
      targetPort: {{ default 8080 $frontend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "rag8s.selectorLabels" . | nindent 4 }}
