{{- /*
Create Namespace resources for every entry in .Values.namespaces.
Support two formats:
1) simple string:   namespaces: { inference: inference }
2) object with name/env/workloadType/annotations:
   namespaces:
     inference:
       name: inference
       workloadType: compute
       env: staging
       annotations: { key: value }

This template always renders a Namespace per map key and uses safe defaults.
*/ -}}
{{- $nsmap := .Values.namespaces | default dict -}}
{{- range $key, $val := $nsmap }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{- if kindIs "string" $val }}{{ $val | quote }}{{- else }}{{ default $key $val.name | quote }}{{- end }}
  labels:
    name: {{- if kindIs "string" $val }}{{ $val | quote }}{{- else }}{{ default $key $val.name | quote }}{{- end }}
    workload-type: {{- if and (not (kindIs "string" $val)) $val.workloadType }}{{ $val.workloadType | quote }}{{- else }}{{ $key | quote }}{{- end }}
    env: {{- if and (not (kindIs "string" $val)) $val.env }}{{ $val.env | quote }}{{- else }}production{{- end }}
  {{- if and (not (kindIs "string" $val)) $val.annotations }}
  annotations:
{{ toYaml $val.annotations | indent 4 }}
  {{- end }}
{{- end }}
