{{- $vals := .Values }}
{{- $ns_inference := (default "inference" $vals.namespaces.inference) }}
{{- $ns_monitoring := (default "monitoring" $vals.namespaces.monitoring) }}
{{- $ns_networking := (default "networking" $vals.namespaces.networking) }}
{{- $ns_vectorDb := (default "vector-db" $vals.namespaces.vectorDb) }}
{{- $ns_graphDb := (default "graph-db" $vals.namespaces.graphDb) }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-sa
  namespace: {{ $ns_inference }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inference-sa-view
  namespace: {{ $ns_inference }}
subjects:
  - kind: ServiceAccount
    name: inference-sa
    namespace: {{ $ns_inference }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: {{ $ns_monitoring }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-sa-view
  namespace: {{ $ns_monitoring }}
subjects:
  - kind: ServiceAccount
    name: monitoring-sa
    namespace: {{ $ns_monitoring }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
