# rag8s-aws/templates/core/serviceaccounts.yaml
# Defines dedicated ServiceAccounts for all namespaces
# ServiceAccounts are linked to AWS IAM Roles via IRSA annotations (for EKS)

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-sa
  namespace: inference
  labels:
    app.kubernetes.io/name: inference-sa
    app.kubernetes.io/part-of: rag8s
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/RAG8sInferenceRole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: indexing-sa
  namespace: indexing
  labels:
    app.kubernetes.io/name: indexing-sa
    app.kubernetes.io/part-of: rag8s
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/RAG8sIndexingRole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stateful-sa
  namespace: stateful
  labels:
    app.kubernetes.io/name: stateful-sa
    app.kubernetes.io/part-of: rag8s
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/RAG8sStatefulRole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring-sa
    app.kubernetes.io/part-of: rag8s
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/RAG8sMonitoringRole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: networking-sa
  namespace: networking
  labels:
    app.kubernetes.io/name: networking-sa
    app.kubernetes.io/part-of: rag8s
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/RAG8sNetworkingRole
