yes proceed. {{- range $key, $sa := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name }}
  namespace: {{ $sa.namespace }}
  labels:
    {{- include "rag8s.labels" $ | nindent 4 }}
  annotations:
    {{- include "rag8s.irsaAnnotations" (dict "Values" (merge .Values (dict "iam" $sa.iam)) "aws" $.Values.aws) | nindent 4 }}
{{- end }}
