{{- $kar := default (dict) .Values.karpenter -}}
{{- $np  := default (dict) (index $kar "nodePool") -}}
{{- $con := default (dict) (index $np "consolidation") -}}
{{- $enabled := default false (index $con "enabled") -}}

{{- if $enabled }}
apiVersion: karpenter.k8s.aws/v1alpha5
kind: Provisioner
metadata:
  name: {{ .Release.Name }}-cpu-provisioner
spec:
  ttlSecondsUntilExpired: {{ default 259200 (index $kar "ttlSecondsUntilExpired") }}
  consolidation:
    enabled: {{ default true (index $con "enabled") }}
  labels:
{{- if (index $np "labels") }}
{{ toYaml (index $np "labels") | indent 4 }}
{{- else }}
    workload-type: cpu
{{- end }}
  taints:
{{- if (index $np "taints") }}
{{ toYaml (index $np "taints") | indent 4 }}
{{- else }}
    # no taints configured
{{- end }}
  limits:
    resources:
{{ toYaml (index (default (dict "resources" (dict "cpu" "200" "memory" "800Gi"))) "resources") | indent 6 }}
{{- end }}
