apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-otel-collector
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-otel-collector
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-otel-collector
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-otel-collector
    spec:
      serviceAccountName: {{ .Release.Name }}-otel-collector-sa
      hostPID: true
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-otel-collector-config
        - name: hostproc
          hostPath:
            path: /proc
            type: Directory
        - name: hostcgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
      containers:
        - name: otel-collector
          image: "{{ .Values.otelCollector.image.repository }}:{{ .Values.otelCollector.image.tag }}"
          imagePullPolicy: {{ .Values.otelCollector.image.pullPolicy }}
          args:
            - "--config=/conf/otel-collector-config.yaml"
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: config
              mountPath: /conf
            - name: hostproc
              mountPath: /host/proc
              readOnly: true
            - name: hostcgroup
              mountPath: /host/sys/fs/cgroup
              readOnly: true
            - name: dockersock
              mountPath: /var/run/docker.sock
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      tolerations:
        - operator: "Exists"
