apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-otel-collector-config
  namespace: {{ .Values.namespace }}
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      hostmetrics:
        collection_interval: 10s
        scrapers:
          cpu: {}
          load: {}
          memory: {}
          disk: {}
          filesystem: {}
          network: {}
          paging: {}
          processes: {}
    processors:
      batch: {}
      resourcedetection:
        detectors: [k8s]
    exporters:
      prometheusremotewrite:
        endpoint: {{ .Values.network.prometheusRemoteWriteEndpoint | default "http://prometheus-receive.monitoring.svc:9090/api/v1/write" }}
      tempo:
        endpoint: {{ .Values.network.tempoEndpoint | default "tempo.monitoring.svc:3200" }}
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resourcedetection]
          exporters: [tempo]
        metrics:
          receivers: [otlp, hostmetrics]
          processors: [batch, resourcedetection]
          exporters: [prometheusremotewrite]
