# values/base.yaml
global:
  namespace: ""   # use .Release.Namespace by default
  labels: {}

aws:
  accountId: ""
iam:
  roleName: ""

karpenter:
  enabled: false

ray:
  enabled: true

qdrant:
  enabled: true

arangodb:
  enabled: true

argocd:
  enabled: false
  namespace: argocd
  project: default
  repoURL: ""
  revision: HEAD
  path: infra/charts/rag8s-aws
  clusterURL: https://kubernetes.default.svc
  prune: true
  selfHeal: true
  override: {}

core:
  pdb:
    embedderReranker:
      enabled: true
      minAvailable: 1
    sglang:
      enabled: false
      minAvailable: 0
    frontend:
      enabled: true
      minAvailable: 1
    qdrant:
      enabled: true
      minAvailable: 1
    arangodb:
      enabled: true
      minAvailable: 1

  quotas:
    # scaled down quotas for 16Gi dev node
    inference:
      enabled: true
      requestsCpu: "250m"
      requestsMemory: "512Mi"
      limitsCpu: "500m"
      limitsMemory: "1Gi"
      pods: "2"
      requestsGPUs: "0"

    indexing:
      enabled: true
      requestsCpu: "500m"
      requestsMemory: "512Mi"
      limitsCpu: "1"
      limitsMemory: "1Gi"
      pods: "1"

    monitoring:
      enabled: false
      requestsCpu: "100m"
      requestsMemory: "256Mi"
      limitsCpu: "250m"
      limitsMemory: "512Mi"
      pods: "1"

    stateful:
      enabled: true
      requestsCpu: "250m"
      requestsMemory: "256Mi"
      limitsCpu: "500m"
      limitsMemory: "512Mi"
      pods: "1"
      pvcs: "1"
      storage: "1Gi"

namespaces:
  inference: inference
  indexing: indexing
  monitoring: monitoring
  networking: networking
  vectorDb: vector-db
  graphDb: graph-db
