# values/karpenter.yaml
karpenter:
  enabled: false

  provider:
    subnetSelector:
      karpenter.sh/discovery: rag8s-eks
    securityGroupSelector:
      karpenter.sh/discovery: rag8s-eks

  gpu:
    weight: 50
    instanceTypes:
      - p3.2xlarge
      - p4d.24xlarge
    capacityTypes:
      - spot
      - on-demand
    amiFamily: AL2
    tags:
      workload: gpu
      env: dev
    limits:
      cpu: "256"
      memory: "1024Gi"
    ttlSecondsAfterEmpty: 60

  cpu:
    weight: 40
    instanceTypes:
      - m6i.large
    capacityTypes:
      - spot
      - on-demand
    amiFamily: AL2
    tags:
      workload: cpu
      env: dev
    limits:
      cpu: "512"
      memory: "2048Gi"
    ttlSecondsAfterEmpty: 60
