# values/monitoring.yaml
monitoring:
  enabled: false
  namespace: ""
  scrapeInterval: "30s"

  grafana:
    enabled: false
    prometheusURL: ""

  serviceMonitors: []
  alerts:
    enabled: false
    groups: []
