# values/qdrant-override.yaml
qdrant:
  enabled: true

  image:
    repository: qdrant/qdrant
    tag: "1.15.1"
    pullPolicy: IfNotPresent

  persistence:
    enabled: true
    storageClass: standard
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  config:
    service:
      http_port: 6333
      grpc_port: 6334
    storage:
      path: /qdrant/storage
    log_level: INFO
    wal_enabled: true
    memory:
      cache_size: 1024  # MB

  nodeSelector: {}
  tolerations: []

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
