# values/ray.yaml
rayservices:
  onnxEmbedderReranker:
    enabled: false
    # disabled by default in dev to save resources

  sglang:
    enabled: false
    # keep disabled for small dev environment (requires GPU)

rayjobs:
  namespace: indexing
  indexing:
    name: rag8s-indexing
    image: myrepo/rag8s-indexer:latest
    entrypoint: "python scripts/index_documents.py --source s3://my-bucket"
    workingDir: "s3://my-bucket/code"
    pip:
      - qdrant-client
      - pandas
      - arango
    ttlSecondsAfterFinished: 3600
    rayVersion: "2.10.0"
    workerReplicas: 1
    workerMin: 1
    workerMax: 1
    resources:
      head:
        cpu: "250m"
        memory: "512Mi"
      worker:
        cpu: "250m"
        memory: "512Mi"

serviceAccounts:
  ray-inference-sa:
    name: ray-inference-sa
    namespace: inference
    iam:
      roleName: ""
