{{- $root := . -}}
{{- $mon := $root.Values.monitoring | default dict -}}
{{- if not (default false $mon.alerts.enabled) -}}
{{- /* monitoring alerts disabled -> nothing to render */ -}}
{{- else -}}
{{- $groups := $mon.alerts.groups | default list -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "rag8s.fullname" $root }}-alerts
  namespace: {{ default $root.Values.namespaces.monitoring $mon.namespace }}
  labels:
    release: prometheus
    {{- include "rag8s.labels" $root | nindent 4 }}
spec:
  groups:
    {{- range $gi, $g := $groups }}
    - name: {{ $g.name }}
      interval: {{ default "30s" $g.interval }}
      rules:
        {{- $rules := $g.rules | default list }}
        {{- range $ri, $r := $rules }}
        - alert: {{ $r.alert }}
          expr: {{ $r.expr | quote }}
          for: {{ default "1m" $r.for }}
          labels:
            severity: {{ default "warning" $r.severity }}
          annotations:
            summary: {{ $r.summary | quote }}
            description: {{ $r.description | quote }}
        {{- end }}
    {{- end }}
{{- end }}
