{{- $root := . -}}
{{- $mon := $root.Values.monitoring | default dict -}}
{{- if not (default false $mon.enabled) -}}
{{- /* monitoring disabled -> render nothing */ -}}
{{- else -}}
{{- $ns := default $root.Values.namespaces.monitoring $mon.namespace -}}
{{- $promURL := default "http://prometheus.monitoring.svc:9090" $mon.grafana.prometheusURL -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rag8s
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: "{{ $promURL }}"
        isDefault: true
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rag8s
    grafana_dashboard: "1"
data:
  # These files must exist in the chart (templates/files or /dashboards in the chart)
  ray-overview.json: |
{{ .Files.Get "dashboards/ray-overview.json" | indent 4 }}
  qdrant-metrics.json: |
{{ .Files.Get "dashboards/qdrant-metrics.json" | indent 4 }}
  arangodb-overview.json: |
{{ .Files.Get "dashboards/arangodb-overview.json" | indent 4 }}
  eks-cluster.json: |
{{ .Files.Get "dashboards/eks-cluster.json" | indent 4 }}
  traefik.json: |
{{ .Files.Get "dashboards/traefik.json" | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rag8s
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'Default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
{{- end }}
