# rag8s-aws/templates/monitoring/grafana.yaml
# Pre-provision Grafana datasources and dashboards

{{- $vals := .Values }}
{{- $nsMonitoring := (default "monitoring" $vals.global.namespace.monitoring) }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ $nsMonitoring }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rag8s
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: {{ $vals.monitoring.grafana.prometheusURL }}
        isDefault: true
        editable: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: {{ $nsMonitoring }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rag8s
    grafana_dashboard: "1"
data:
  ray-overview.json: |
{{ .Files.Get "dashboards/ray-overview.json" | indent 4 }}
  qdrant-metrics.json: |
{{ .Files.Get "dashboards/qdrant-metrics.json" | indent 4 }}
  arangodb-overview.json: |
{{ .Files.Get "dashboards/arangodb-overview.json" | indent 4 }}
  eks-cluster.json: |
{{ .Files.Get "dashboards/eks-cluster.json" | indent 4 }}
  traefik.json: |
{{ .Files.Get "dashboards/traefik.json" | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: {{ $nsMonitoring }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rag8s
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'Default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
