{{- /*
Grafana ConfigMaps (datasources, dashboards, provisioning).
- Renders only when monitoring.enabled && monitoring.grafana.enabled
- Uses .Values.monitoring.grafana.dashboards (map name->path). If unset, falls back to defaults.
- Skips missing dashboard files.
*/ -}}
{{- $root := . -}}
{{- $mon := $root.Values.monitoring | default dict -}}
{{- if and (default false $mon.enabled) (default false $mon.grafana.enabled) -}}
{{- $ns := default $root.Values.namespaces.monitoring $mon.namespace -}}
{{- $promURL := default "http://prometheus.monitoring.svc:9090" $mon.grafana.prometheusURL -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ $ns | quote }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rag8s
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: "{{ $promURL }}"
        isDefault: true
        editable: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: {{ $ns | quote }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rag8s
    grafana_dashboard: "1"
data:
{{- /*
Collect dashboards from values.monitoring.grafana.dashboards (map) if provided,
otherwise use a safe defaults map. For each entry only render if the file exists.
*/ -}}
{{- $userDashboards := $mon.grafana.dashboards | default dict -}}
{{- $defaults := dict
     "ray-overview.json" "dashboards/ray-overview.json"
     "arangodb-overview.json" "dashboards/arangodb-overview.json"
     "eks-cluster.json" "dashboards/eks-cluster.json"
     "traefik.json" "dashboards/traefik.json"
 -}}

{{- if gt (len $userDashboards) 0 }}
  {{- range $fname, $path := $userDashboards }}
    {{- $content := $root.Files.Get $path | trim }}
    {{- if ne $content "" }}
  {{ $fname }}: |
{{ $content | indent 4 }}
    {{- end }}
  {{- end }}
{{- else }}
  {{- range $fname, $path := $defaults }}
    {{- $content := $root.Files.Get $path | trim }}
    {{- if ne $content "" }}
  {{ $fname }}: |
{{ $content | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: {{ $ns | quote }}
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: rag8s
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'Default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
{{- end }}
