{{- $root := . -}}
{{- $mon := $root.Values.monitoring | default dict -}}
{{- if not (default false $mon.enabled) -}}
{{- /* monitoring disabled -> no ServiceMonitors rendered */ -}}
{{- else -}}
{{- $list := $mon.serviceMonitors | default list -}}
{{- range $i, $sm := $list }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $sm.name }}
  namespace: {{ default $root.Values.namespaces.monitoring $sm.namespace }}
  labels:
    {{- include "rag8s.labels" $root | nindent 4 }}
spec:
  selector:
    matchLabels:
{{ toYaml $sm.matchLabels | nindent 6 }}
  endpoints:
    - port: {{ $sm.port }}
      {{- if $sm.path }}
      path: {{ $sm.path }}
      {{- end }}
      interval: {{ default $root.Values.monitoring.scrapeInterval $sm.interval | default "30s" }}
---
{{- end }}
{{- end }}
