# rag8s-aws/templates/monitoring/servicemonitors.yaml
# ServiceMonitors for Prometheus Operator to scrape metrics from various components

{{- range .Values.monitoring.serviceMonitors }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    {{- include "rag8s-aws.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- toYaml .matchLabels | nindent 6 }}
  endpoints:
    - port: {{ .port }}
      {{- if .path }}
      path: {{ .path }}
      {{- end }}
      interval: {{ .interval | default "30s" }}
{{- end }}
