apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: indexing-cronjob
  namespace: argocd
  labels:
    app.kubernetes.io/name: indexing-cronjob
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: e2e-rag-system
  annotations:
    description: Indexing CronJob Helm deployment
    deployed-at: "2026-05-14T13:01:03Z"
    aws-region: "ap-south-1"
    ecr-repository: "681802563986.dkr.ecr.ap-south-1.amazonaws.com/indexer"
spec:
  project: default
  source:
    repoURL: https://github.com/Athithya-Sakthivel/E2E-RAG-System.git
    targetRevision: main
    path: src/infra/helm/indexing_cronjob
    helm:
      values: |
        image:
          registry: 681802563986.dkr.ecr.ap-south-1.amazonaws.com
          repository: indexer
          tag: "staging"
          pullPolicy: IfNotPresent
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::681802563986:role/rag-indexer-irsa-role"
        env:
          S3_BUCKET: "rag-staging-qdrant-backups-681802563986"
          DATA_S3_BUCKET: "rag-staging-data-681802563986"
        resources:
          requests:
            cpu: "500m"
            memory: 512Mi
          limits:
            cpu: "2"
            memory: 2Gi
        nodeSelector:
          node-type: compute
        tolerations:
          - key: "node-type"
            operator: "Equal"
            value: "compute"
            effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: indexing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
