apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  sources:
    - repoURL: public.ecr.aws/karpenter
      chart: karpenter
      targetRevision: 1.9.0
      helm:
        values: |
          serviceAccount:
            create: true
            name: karpenter
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::681802563986:role/rag-eks-staging-karpenter
          settings:
            clusterName: rag-eks-staging
            clusterEndpoint: https://1D7C59A179505790ECF1FDD8C71BBD61.gr7.ap-south-1.eks.amazonaws.com
    - repoURL: https://github.com/Athithya-Sakthivel/E2E-RAG-System.git
      targetRevision: main
      path: src/manifests/karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
