# values.kind.yaml (local single-node kind testing)
namespace:
  create: true
  name: embedder

image:
  repository: "embedder-cpu-inference"
  tag: "local"
  pullPolicy: Never
  pullSecret:
    enabled: false

replicaCount: 1

service:
  type: ClusterIP
  port: 8000
  host: "0.0.0.0"

server:
  maxLength: 500
  maxBatch: 16
  batchWaitS: 0.03

# For kind, use hostPath to a path inside the kind node container; ensure you populate it.
model:
  path: "/workspace/models"
  usePVC: false
  useHostPath: true
  readOnly: true
  hostPath:
    path: "/kind-models"       # must exist on the kind node (or use DirectoryOrCreate)
    type: DirectoryOrCreate
  initContainer:
    enabled: false

# No nodeSelector for kind (single node)
nodeSelector: {}
tolerations: []

podSecurity:
  runAsUser: 1000
  fsGroup: 1000

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# Prometheus disabled by default for kind
metrics:
  prometheusAutoScrape: false
  serviceMonitor:
    enabled: false

hpa:
  enabled: false

pdb:
  minAvailable: 1

networkPolicy:
  enabled: false

serviceAccount:
  name: embedder-sa

# Keep empty so image CMD is used
container:
  command: []
  args: []

probes:
  readiness:
    path: /health
    initialDelaySeconds: 20
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 5
  liveness:
    path: /health
    initialDelaySeconds: 60
    timeoutSeconds: 5
    periodSeconds: 30
    failureThreshold: 5
