# Default values for rag8s-onnx Helm chart.
# IMPORTANT: do NOT put secrets / tokens here in SCM. Use external secret manager
# or pass via `--set` at deploy time.

image:
  repository: rag8s/rag8s-onnx-embedder-reranker-cpu-amd64
  tag: gte-modernbert
  pullPolicy: IfNotPresent

# Ray version must match the Ray included in the image
rayVersion: "2.48.0"

# Resource defaults for head & worker pods (tweak per cluster capacity)
replicaDefaults:
  head:
    resources:
      requests:
        cpu: "2"
        memory: "4Gi"
      limits:
        cpu: "4"
        memory: "8Gi"
  worker:
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "4Gi"

# Serve application config (import_path)
serve:
  importPath: "rayserve_entrypoint:app"
  httpPort: 8000
  grpcPort: 9000
  deployments:
    embedder:
      num_replicas: 1
      ray_actor_num_cpus: 1
      autoscaling:
        min_replicas: 1
        max_replicas: 4
        target_num_ongoing_requests_per_replica: 10
    reranker:
      num_replicas: 1
      ray_actor_num_cpus: 1
      autoscaling:
        min_replicas: 1
        max_replicas: 2
        target_num_ongoing_requests_per_replica: 5

# ONNX & batching knobs; read by the code and overridable here
env:
  HF_HOME: "/app/models/hf"
  MODEL_EMBEDDER_NAME: "RAG8s/gte-modernbert-base-onnx-int8"
  MODEL_RERANKER_NAME: "RAG8s/gte-reranker-modernbert-base-onnx-int8"
  EMBEDDER_OMP_NUM_THREADS: "1"
  RERANKER_OMP_NUM_THREADS: "1"
  EMBEDDER_BATCH_MAX_SIZE: "8"
  RERANKER_BATCH_MAX_SIZE: "4"
  EMBEDDER_BATCH_WAIT_TIMEOUT_S: "0.05"
  RERANKER_BATCH_WAIT_TIMEOUT_S: "0.1"

# Secrets: only secret NAME here. DO NOT commit the secret value.
secrets:
  hfTokenSecretName: rag8s-hf-token

# Probes (readiness/liveness)
probes:
  readiness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    path: /healthz
    initialDelaySeconds: 60
    periodSeconds: 15
    failureThreshold: 5

prometheus:
  enabled: true

rbac:
  create: true

podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Pod tuning
terminationGracePeriodSeconds: 120
