apiVersion: v1
kind: Secret
metadata:
  name: authentik-blueprints
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: blueprints
type: Opaque
stringData:
  google-oauth-forward-auth.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    version: 1
    metadata:
      name: athithya-authentik-bootstrap
    entries:
      - model: authentik_sources_oauth.oauthsource
        state: present
        identifiers:
          slug: google
        attrs:
          name: Google
          slug: google
          provider_type: google
          consumer_key: !Env GOOGLE_OAUTH_CLIENT_ID
          consumer_secret: !Env GOOGLE_OAUTH_CLIENT_SECRET
          scope: openid email profile
          enabled: true

      - model: authentik_providers_proxy.proxyprovider
        state: present
        identifiers:
          slug: api-forward-auth
        attrs:
          name: api-forward-auth
          slug: api-forward-auth
          mode: forward_single_application
          external_host: https://api.athithya.site

      - model: authentik_core.application
        state: present
        identifiers:
          slug: api-forward-auth
        attrs:
          name: api-forward-auth
          slug: api-forward-auth
          provider: !Find [authentik_providers_proxy.proxyprovider, [slug, api-forward-auth]]
