global:
  envFrom:
  - secretRef:
      name: authentik-env
  env:
  - name: AUTHENTIK_HOST
    value: https://auth.athithya.site
  - name: AUTHENTIK_HOST_BROWSER
    value: https://auth.athithya.site
  - name: AUTHENTIK_COOKIE_DOMAIN
    value: .athithya.site
  - name: AUTHENTIK_POSTGRESQL__HOST
    value: authentik-postgresql
  - name: AUTHENTIK_POSTGRESQL__PORT
    value: '5432'
  - name: AUTHENTIK_POSTGRESQL__USER
    value: authentik
  - name: AUTHENTIK_POSTGRESQL__NAME
    value: authentik
authentik:
  enabled: true
  existingSecret:
    secretName: authentik-env
  log_level: info
  error_reporting:
    enabled: false
  web:
    path: /
  postgresql:
    host: authentik-postgresql
    name: authentik
    user: authentik
    port: 5432
    password: env://AUTHENTIK_POSTGRESQL__PASSWORD
server:
  enabled: true
  ingress:
    enabled: false
worker:
  enabled: true
blueprints:
  secrets:
  - name: authentik-blueprints
postgresql:
  enabled: true
  auth:
    username: authentik
    database: authentik
    existingSecret: authentik-postgresql-auth
    secretKeys:
      adminPasswordKey: postgres-password
      userPasswordKey: password
      replicationPasswordKey: replication-password
      metricsPasswordKey: metrics-password
