apiVersion: kubeai.org/v1
kind: Model
metadata:
  name: gte-micro-cpu
spec:
  features:
    - TextEmbedding
  owner: community
  url: "hf://Mihaiii/gte-micro"
  engine: Infinity
  resourceProfile: cpu:1
  minReplicas: 1
  maxReplicas: 2
  cacheProfile: default
