{{- $root := . -}}
{{- $pol := $root.Values.network.policies | default dict -}}
{{- if not (default false $pol.enabled) -}}
{{- /* network policies disabled -> nothing to render */ -}}
{{- else -}}
{{- $rules := $pol.rules | default list -}}
{{- range $i, $r := $rules }}
{{- $ns := default $root.Release.Namespace (default $root.Values.namespaces.networking $r.namespace) -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $r.name }}
  namespace: {{ $ns }}
  labels:
    app.kubernetes.io/name: {{ $r.name | quote }}
    app.kubernetes.io/part-of: rag8s
    {{- include "rag8s.labels" $root | nindent 4 }}
spec:
  podSelector:
    {{- if $r.podSelector }}
{{ toYaml $r.podSelector | nindent 4 }}
    {{- else }}
    {}
    {{- end }}
  {{- if $r.policyTypes }}
  policyTypes:
{{ toYaml $r.policyTypes | nindent 4 }}
  {{- else }}
  policyTypes:
    {{- if $r.ingress }}
    - Ingress
    {{- end }}
    {{- if $r.egress }}
    - Egress
    {{- end }}
  {{- end }}
  {{- if $r.ingress }}
  ingress:
{{ toYaml $r.ingress | nindent 4 }}
  {{- end }}
  {{- if $r.egress }}
  egress:
{{ toYaml $r.egress | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
