EmbedderReranker:
  image:
    repository: rag8s/rag8s-onnx-embedder-reranker-cpu
    tag: latest
    pullPolicy: IfNotPresent

  rayVersion: "2.48.0"

  embedder:
    numCPUs: 1
    minReplicas: 1
    maxReplicas: 4
    targetOngoingRequestsPerReplica: 10

  reranker:
    numCPUs: 1
    minReplicas: 1
    maxReplicas: 2
    targetOngoingRequestsPerReplica: 5
