apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: compute
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@latest
  role: KarpenterNodeRole-rag-eks-staging
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: rag-eks-staging
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: rag-eks-staging
  tags:
    karpenter.sh/discovery: rag-eks-staging
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
