apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-routes-reference
  namespace: inference
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/component: tunnel-reference
data:
  routes.yaml: |
    tunnel: default-tunnel-1
    ingress:
    - hostname: auth.athithya.site
      service: http://authentik-server.authentik.svc.cluster.local:80
    - hostname: api.athithya.site
      service: http://frontend-nginx.inference.svc.cluster.local:8080
    - hostname: athithya.site
      service: http://frontend-nginx.inference.svc.cluster.local:8080
    - service: http_status:404
