name: Build, scan, push ONNX image (infra/onnx)

on:
  push:
    paths:
      - 'infra/onnx/**'
  workflow_dispatch:

env:
  IMAGE_REPO: rag8s/rag8s-onnx-embedder-reranker-cpu-amd64

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push ONNX image
        uses: docker/build-push-action@v4
        with:
          context: ./infra/onnx
          file: ./infra/onnx/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ github.sha }}
            ${{ env.IMAGE_REPO }}:gte-modernbert
            ${{ env.IMAGE_REPO }}:latest

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.18.0
        with:
          image-ref: ${{ env.IMAGE_REPO }}:latest
          format: table
          exit-code: 1
          ignore-unfixed: true

      - name: Run smoke test
        run: |
          docker run --rm \
            -e HF_TOKEN=${{ secrets.HF_TOKEN }} \
            ${{ env.IMAGE_REPO }}:latest \
            bash infra/onnx/tests/smoke_test.sh
