{{- if and .Values.retriever.enabled .Values.retriever.networkPolicy }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: retriever
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: retriever
  policyTypes:
    - Ingress
    - Egress
  ingress:
  {{- range .Values.retriever.networkPolicy.ingressAllowFrom }}
    - from:
      {{- if .podLabels }}
        - podSelector:
            matchLabels:
              {{- toYaml .podLabels | nindent 14 }}
      {{- end }}
      {{- if .namespaceLabels }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .namespaceLabels | nindent 14 }}
      {{- end }}
      ports:
      {{- range .ports }}
        - protocol: TCP
          port: {{ . }}
      {{- end }}
  {{- end }}
  egress:
  {{- range $target, $rule := .Values.retriever.networkPolicy.egressAllowTo }}
    - to:
      {{- if eq $target "internet" }}
        - ipBlock:
            cidr: {{ $rule.cidr }}
            {{- if $rule.except }}
            except:
              {{- toYaml $rule.except | nindent 14 }}
            {{- end }}
      {{- else }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml $rule.namespaceLabels | nindent 14 }}
          podSelector:
            matchLabels:
              {{- toYaml $rule.podLabels | nindent 14 }}
      {{- end }}
      ports:
      {{- if eq $target "dns" }}
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
      {{- else }}
      {{- range $rule.ports }}
        - protocol: TCP
          port: {{ . }}
      {{- end }}
      {{- end }}
  {{- end }}
{{- end }}